### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-components-vue#17]
## Rationale

A modal is a common component in every design system. It represents a window that opens in the middle of the screen, on top of everything else and with a dark overlay.

## Description

Add a modal component to ripe-components-vue which has:
* Title
* Sub-title
* Close button
* Action buttons (might be 0, 1, 2 or more)

Inspiration:
* https://dribbble.com/shots/4907323-Saver-redesigned
* https://dribbble.com/shots/6276685--Edit-tabs-modal-for-CoderHub
* http://developer.royalcanin.com/ui-framework/elements/modal.html
* https://styleguide.auth0.com/components/modals

## Implementation

**Comment by joamag** [comment]
This is now considered done
