### ISSUE TITLE
Select component closing bug

### ISSUE THREAD

**Issue by jorgefernandess** [ripe-tech/ripe-components-vue#273]
## Description

The [select component](https://ripe-components-vue-git-master.platforme.now.sh/?path=/story/molecules--select) is not closing when another selector is clicked.
 
## Repro Steps

1st - Access sputnik
2nd - Create a new job
3rd - Select device and preset 

## Screens

![2020-02-21 12 08 28](https://user-images.githubusercontent.com/57152582/75033492-f4664680-54a2-11ea-9477-39c18746d7f7.gif)

**Comment by gcandal** [comment]
For whoever picks this up: clicking outside a `dropdown` should close it. The only reason I can think of that not happening is that something (probably inside the `dropdown`) is stopping the propagation of the event, so review that.
