### ISSUE TITLE
Use container header on all consumers

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-components-vue#294]
## Description

[This PR](https://github.com/ripe-tech/ripe-pulse/pull/114) demonstrates the usage of the `container-ripe#title` which should be applied to all other places where we have a duplicated `container-header` class.

**@todo we need to add more information and implementation guidelines**

**Comment by gcandal** [comment]
@NFSS10 let's add `header-buttons`  to the `container` before closing this.

**Comment by NFSS10** [comment]
> @NFSS10 let's add `header-buttons` to the `container` before closing this.

Working on it !

**Comment by gcandal** [comment]
@NFSS10 is this `Doing` or `In Review`?

**Comment by NFSS10** [comment]
> @NFSS10 is this `Doing` or `In Review`?

@gcandal "Doing", as it still needs to be decided what to do with the `header-buttons` in `details-ripe` when in mobile

**Comment by joamag** [comment]
@gcandal We really need to talk about this issue as a whole as this is a `p-low` issue that is creating a lot of PRs and work. On top of that, this issue was no properly validated by myself on triage. Let's use the Monday timeslot to re-discuss this one.
