### ISSUE TITLE
RIPE Pulse Mobile menu Bug

### ISSUE THREAD

**Issue by jorgefernandess** [ripe-tech/ripe-components-vue#305]
## Description

RIPE Pulse Mobile app switcher is changing it's position when clicked.
The component's width doesn't fit in the menu.

## Repro Steps

* Open RIPE Pulse Mobile version
* Click in app switcher

## Screens

![2020-05-13 14 46 09](https://user-images.githubusercontent.com/57152582/81820516-9fc5eb00-9528-11ea-87b8-583e3e2a3a5b.gif)

**Comment by gcandal** [comment]
@jorgefernandess when opening bugs, assign them to @joamag with the `Triage` label.

**Comment by joamag** [comment]
@gcandal I know we've fixed this in the past. We need to find a better solution this time ;)

**Comment by joamag** [comment]
@jorgefernandess congrats on your first bug opening!

**Comment by gcandal** [comment]
@FlaviooLima give this one a go!

**Comment by FlaviooLima** [comment]
@gcandal aye aye
