### ISSUE TITLE
RIPE White Swatch glitch

### ISSUE THREAD

**Issue by jorgefernandess** [ripe-tech/ripe-components-vue#309]
## Description

RIPE White glitches with some material images.

## Repro Steps

1 - Open this [link](https://ripe-white-now.platforme.com/?brand=sergio_rossi&model=sr1_pump075&p=sole%3Aleather_sr%3Ablack&p=lining%3Acalf_lining_sr%3Abeige&p=upper%3Acavallino_sr%3Apony_dots&p=plate%3Ametal_sr%3Agold24&p=shadow%3Adefault%3Adefault).

2 - Choose the following materials:
- Upper > Lace > Bianco
- Upper > Naplys Elaphe > Natur

## Screens

![2020-05-21 11 54 08](https://user-images.githubusercontent.com/57152582/82552393-ea171f80-9b59-11ea-9c29-930a4062c0e6.gif)

**Comment by gcandal** [comment]
@jorgefernandess when opening new tickets, use the `triage` label and assign it to @joamag

**Comment by joamag** [comment]
This is OK and related with CSS. Closing as won't fix.

@jorgefernandess please don't forget about the triage labels and proper allocation to myself
