### ISSUE TITLE
Input list

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-components-vue#410]
## Description

**Base issue**: https://github.com/ripe-tech/ripe-core/issues/4425

Create a component that enables users to input several entities that respect a schema.

Interactions:
- Add row
- Remove row
- Edit row

Props:
- fields: list of objects with `value` (logical name of the fields), `type, `meta`, `label` (user-facing name, if not present uses `value`). Check https://github.com/ripe-tech/ripe-components-vue/blob/a03e5314a19beef0c126146f499d5aa373fbd3f6/vue/components/ui/organisms/form/form.vue for possible configurations
- values (syncable): list of objects. Each one is a key-value object. E.g.: `[{gender: male, scale: FR, sizes: [10] }, { gender: null, scale: null, size: null }]`

Visual:

![image](https://user-images.githubusercontent.com/3048875/101667098-d4f6d500-3a46-11eb-82d6-b7bf0badde27.png)

**Comment by joamag** [comment]
@gcandal This is a complex component for which the strategy should be previously validated
