### ISSUE TITLE
Container is too large

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-components-vue#433]
## Description

There was a UI regression in most pages that seems to have been caused by https://github.com/ripe-tech/ripe-components-vue/commit/5c9b0c3d5235a19ef4011a0446ee47f0f779fbeb .

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | The central container to have 1240px. |
| **Observed** | The central container has untilimited width. |

## Repro Steps

1. Go to localhost:3000/orders (or any RIPE Pulse running on ripe-components-vue >=0.8.7)

## Screens

Before:

![image](https://user-images.githubusercontent.com/3048875/105576940-47f5aa00-5d6e-11eb-9069-c91a819460cd.png)

After:

![image](https://user-images.githubusercontent.com/3048875/105576945-4cba5e00-5d6e-11eb-849c-cba6e41d330e.png)

**Comment by joamag** [comment]
The https://github.com/ripe-tech/ripe-components-vue/commit/5c9b0c3d5235a19ef4011a0446ee47f0f779fbeb "fix" is related to regressions in mobile layouts. We'll have to figure out how can we handle this stuff.
