### ISSUE TITLE
Show notifications in entity components

### ISSUE THREAD

**Issue by BeeMargarida** [ripe-tech/ripe-components-vue#467]
## Rationale

In the components `entity-show` and `entity-list` its normally necessary to show confirmation of actions that happened before going to the page. For example, when creating an entity in `entity-create`, it will then redirect to `entity-list` which now contains the new entity. To confirm that the new entity was created, its normal to use the `notify` component to show a message like "Entity created". 

With the component as is, this feature has to be implemented in the pages that use them. Since its so common, it would be beneficial if the components already handled this behavior.

Originated from https://github.com/ripe-tech/ripe-twitch-admin-ui/pull/4#issuecomment-804841789

## Description

Components `entity-show` and `entity-list` read the URL query and extract the notification text. If its defined, show a notification with the text, icon and icon color (these icon attributes can be overridden by props).

Components `entity-create` send notification text per default to the `next` route. (`entity-edit` should also do this but since for now its not handling any redirecting logic, this might come in the future).

## Software Engineering

A possible solution may be:

In `entity-create`
- Change the code below to send a query param like `notifyText` that has the text `${this.name} Created`: https://github.com/ripe-tech/ripe-components-vue/blob/eb47a7c85457c425c44ccd765e4e1f17c9cd4eae/vue/components/ui/organisms/entity-create/entity-create.vue#L118-L125

In `entity-show` and `entity-list`:
- In the `mounted` hook, add code similar to the one below, so that it gets the notification text from the query params and shows it.
```
const params = this.$route.params;
if (!params.notifyText) return;
await this.notify(text, {
    icon: this.notificationIcon,
    iconColor: this.notificaitonColor,
    timeout: params.notifyText
});
```
- Handle notification icon and color props

## Reference

This feature originated from designs:
- https://www.figma.com/file/hPk9OTE7dKzdaIR4pCB2ml/RIPE-Twitch-Public?node-id=1582%3A5239
- https://www.figma.com/file/hPk9OTE7dKzdaIR4pCB2ml/RIPE-Twitch-Public?node-id=1582%3A5424
- https://www.figma.com/file/hPk9OTE7dKzdaIR4pCB2ml/RIPE-Twitch-Public?node-id=1582%3A5757

## Estimation

| Discipline | Estimation |
| --- | --- |
| **UI/UX Design** | -- |
| **Software Development** | 1 hour |

**Comment by joamag** [comment]
I've discussed this with @gcandal I don't believe we'll need this for now.
@gcandal knows how we're going to handle these "pulse" notifications in a more simplified fashion
