### ISSUE TITLE
Fix deprecation warning

### ISSUE THREAD

**Issue by gcandal** [ripe-tech/ripe-components-vue#468]
## Description

Several of our Vue-powered products are getting this warning:

```
[vue-router] In Vue Router 4, the v-slot API will by default wrap its content with an <a> element. Use the custom prop to remove this warning:
<router-link v-slot="{ navigate, href }" custom></router-link>
```

This should be fixed across all repos so that we're safeguarded against an eventual vue-router upgrade and don't have unpleasant surprises.

**Comment by joamag** [comment]
@gcandal let's first validate one simple case and the propagate this

**Comment by beneditomauro** [comment]
https://github.com/search?p=1&q=org%3Aripe-tech+%3Crouter-link&type=Code

I think I covered them all
