### ISSUE TITLE
Create new component

### ISSUE THREAD

**Issue by dsafonso** [ripe-tech/ripe-components-vue#571]
## Rationale

Create a new component that group's avatars that have max used to calculate the extra avatar. the extra should be the last element and be displayed

## Description

Create a new component that group's avatars that have max used to calculate the extra avatar. the extra should be the last element and be displayed like this:
<img width="191" alt="Screen Shot 2022-03-29 at 10 43 48" src="https://user-images.githubusercontent.com/20085/160584480-3811ee66-fa5a-444b-b473-d227ecb062bb.png">

## Estimation

| Discipline | Estimation |
| --- | --- |
| **UI/UX Design** | X days  |  
| **Software Development** | 2 days |
| **QA** | 0.5 days |

**Comment by veryprofessionaldodo** [comment]
@hugo-gomes Regarding this issue, looking at the design, are all avatars meant to be slightly overlapping, or is it just one group of (for example) 3 avatars, with one of the circles being the `+5`? If all of them are meant to be overlapping, it probably will generate too much visual noise when 40 or so avatars are displayed at once.

**Comment by dsafonso** [comment]
Test OK :+1:
