### ISSUE TITLE
`vue-loader` 15.10.0 warnings that `::v-deep` is deprecated

### ISSUE THREAD

**Issue by 3rdvision** [ripe-tech/ripe-components-vue#605]
## Description

Recently after 15.10.0 vue-loader release we're getting warnings when doing the webpack build related to the fact that `::v-deep` has been deprecated. It looks like the deprecation comes from Vue 3 but we're still using Vue 2 so we might consider fixing the version of vue-loader to the latest without warnings which is "vue-loader": "15.9.8" until we migrate everything to Vue 3.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | vue-loader builds without warnings |
| **Observed** | vue-loader builds with warnings related to Vue 3. |

## Repro Steps

1. Git clone ripe-components-vue master with `git clone https://github.com/ripe-tech/ripe-components-vue.git`
2. Install and build the project with `yarn && yarn watch`
3. See the warnings in the console appear

## Important notes

We have [43 ripe containers](https://github.com/search?l=JSON&p=5&q=org%3Aripe-tech+vue-loader&type=Code) using vue-loader as a dependency with `^15.9.8`. A fix could be to change it to `~15.9.8`.

## Screens

![image](https://user-images.githubusercontent.com/24736423/184099378-b2e6b035-bc21-479b-9a2b-c12b55f73c69.png)

**Comment by 3rdvision** [comment]
Related
- https://github.com/ripe-tech/ripe-components-vue/issues/597

**Comment by joamag** [comment]
Let's try to orchestrate this with https://github.com/ripe-tech/ripe-components-vue/issues/597

**Comment by msp-platforme** [comment]
> We have [43 ripe containers](https://github.com/search?l=JSON&p=5&q=org%3Aripe-tech+vue-loader&type=Code) using vue-loader as a dependency with **^15.9.8**. A fix could be to change it to **^15.9.8**.

Can you explain me what is the change then? :confused:

**Comment by 3rdvision** [comment]
> > We have [43 ripe containers](https://github.com/search?l=JSON&p=5&q=org%3Aripe-tech+vue-loader&type=Code) using vue-loader as a dependency with **^15.9.8**. A fix could be to change it to **^15.9.8**.

> Can you explain me what is the change then? confused

Glad you asked as I wanted to say that a fix could be to change it to **~15.9.8** instead of the current **^15.9.8**. Fixed in the main thread :smile:

**Comment by 3rdvision** [comment]
Since https://github.com/ripe-tech/ripe-components-vue/issues/597 is most likely a no-go issue I'd suggest still fixing this warning by following the suggested fix in [here](https://github.com/ripe-tech/ripe-components-vue/issues/605#issuecomment-1229986490).

**Comment by NFSS10** [comment]
Is this still revelant? Can't seem to reproduce:
![image](https://user-images.githubusercontent.com/22588915/213204614-294019d8-985c-4641-a418-a6043bdd2a39.png)

**Comment by 3rdvision** [comment]
> Is this still relevant? I can't seem to reproduce:

Maybe this was already fixed in the latest minor version.
@NFSS10 Did you do a clean install before `yarn watch`?

**Comment by NFSS10** [comment]
> Maybe this was already fixed in the latest minor version. @NFSS10 Did you do a clean install before `yarn watch`?

Yes!

**Comment by 3rdvision** [comment]
> Yes!

Confirmed to be working on my side as well:
![image](https://user-images.githubusercontent.com/24736423/213246034-cb21a3db-751d-496a-a6c4-2dff8fd4f29b.png)

Closing this as it was solved in [vue-loader](https://github.com/vuejs/vue-loader) and is no longer reproducible.
