### ISSUE TITLE
`upload-area` component not clearing data

### ISSUE THREAD

**Issue by beneditomauro** [ripe-tech/ripe-components-vue#612]
## Description

The component doesn't clear the data when you select the file by the button

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | After clearing data I should be able to select other files |
| **Observed** | After clearing data we are not able to select other files |

## Repro Steps

1. Select file with button
2. Clear the data
3. Try to select another

## Environment

| Key | Value |
| --- | --- |
| **Device** | iMac (Retina 5K, 27-inch, 2019) |
| **Operating System** | mac OS Monterey 12.5|
| **Browser** |  Google Chrome Version 106.0.5249.119 (Official Build) (x86_64) |

## Screens

![uMZO5Mt4HW](https://user-images.githubusercontent.com/8842023/198033154-d3415df8-3606-41f3-a3bb-2a3a7d194cf3.gif)

**Comment by joamag** [comment]
Closing this as verified. @msp-platforme sparing you from this one :)
